[project]
name = "dynamicheatcontrol"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "influxdb>=5.3.2",
    "requests>=2.32.4",
    "urllib3>=2.2.3",
]
